parameters:
#    jazzyweb_aulas_mentor_alimentos.example.class: Jazzyweb\AulasMentor\AlimentosBundle\Example

services:
#    jazzyweb_aulas_mentor_alimentos.example:
#        class: %jazzyweb_aulas_mentor_alimentos.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
